# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFramework' do
  platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'YandexCheckoutPayments',
    :git => 'https://github.com/yandex-money/yandex-checkout-payments-swift.git',
    :tag => '2.2.0'

end
