# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFramework' do
  platform :ios, '9.0'
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'YandexCheckoutPayments',
    :git => 'https://github.com/yandex-money/yandex-checkout-payments-swift.git',
    :tag => '2.2.0'

  pod 'YandexLoginSDK',
    :git => 'https://github.com/yandexmobile/yandex-login-sdk-ios',
    :tag => '2.0.2',
    :modular_headers => true

  pod 'React', :path => '../example/node_modules/react-native'
  pod 'React-Core', :path => '../example/node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../example/node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../example/node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../example/node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../example/node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../example/node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../example/node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../example/node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../example/node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../example/node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../example/node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../example/node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../example/node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../example/node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../example/node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../example/node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../example/node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../example/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../example/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../example/node_modules/react-native/third-party-podspecs/Folly.podspec'
end
